### ISSUE TITLE
issues setting up this project in moonriver studio

### ISSUE THREAD

**Issue by Nout1** [AdiHamulic/CH32V003-SPI-DMA---ILI9341#1]
I'm trying to get the code running in mounriver studio, but have some problems
steps I made:
create a new project in mounriver studio
copied the following files from GitHub to the user directory in moon river
main.c
colors.h
fonts.c and fonts.h
ill9341.c and ili9341.h
delay.c and delay.h
spi.c and spi.h
uart.c and uart.h
 compiling finalized without any errors
upload to ch32v003f4p6 gives no errors
the TFT screen remains black, nothing happens

to ensure everything is hooked up correctly, I uploaded the hex file from GitHub
the display shows the expected demo from youtube but distorted. it seems like a mixup in addressing the correct pixels, but I can recognize a shifted menu, filling background, filling boxes etc... maybe x and y are swapped?
anyway, I conclude from this that with the given wiring the display should work and at least show the same distorted views, but it remains black.

so I started to compare the system files and see some limited differences exist, since my files seem to be more recent
I'm not keen on touching these files

so can you tell me if you "on purpose" made any required changes to the system file?
ch32v00x.h and .c
ch32v00x_it.h and .c
ch32v00x_conf.h and .c
system_ch32v00x.h and .c

**Comment by AdiHamulic** [comment]
Only in file ch32v00x_it.c  I have added counter in SysTick_Handler function, for delay_ms() purpose. Rest of the files were left unchanged.  
So first check is delay function working correctly.

**Comment by Nout1** [comment]
I've added the following lines to ch32v00x_it.c 
`extern volatile uint32_t delay_cnt;`

 and

`void SysTick_Handler(void)
{
	SysTick->SR = 0;
	if (delay_cnt > 0) delay_cnt--;
}`

I also added

`void SysTick_Handler(void) __attribute__((interrupt("WCH-Interrupt-fast")));`

to ch32v00x_it.h

after compilation, I now get the same distorted views as I got uploading the hex file from GitHub
that solves one problem
PS: debug.h does support by nature a delay_Ms function. Is there a reason why that function was not used?

As next step, i now need to find out the reason why the data is distorted.
I have swap screen size from 240x320 to 320x240 and that makes a change but did not solves the distortion
any other hints are welcome

**Comment by AdiHamulic** [comment]
I always try to create a project as little as possible, so maybe in the beginning I just removed debug.h and create functions I just need. 

If you can upload picture of display, from back and front (with distorted image ).

**Comment by Nout1** [comment]
Except for the distortion, the full demo seems to works fine, so I did not strip it down

but the good news is that I found the problem, and it's a stupid one.... Shame on me!
I've accidentally used a display based on st7735 which looks nearly identical as the one using ili9341
anyway, you helped me a lot by pointing to the delay function and everything works now
thanks !

**Comment by AdiHamulic** [comment]
That's good, you find a problem :) . Many of the display from China have almost identical look and specs, but controllers in many cases are different.
Unfortunately I didn't implemented a function for checking display controller. Maybe later when I have more time :)

**Comment by Nout1** [comment]
have you build any code to add touch xpt2045?

**Comment by AdiHamulic** [comment]
No, I haven't.
